// frontend/src/routes/(app)/startups/+page.svelte
<script lang="ts">
  import { Skeleton } from '$lib/components/ui/skeleton';
  import Button from '$lib/components/ui/button/button.svelte';
  import { RocketIcon } from 'lucide-svelte';
  import { StartupCard } from '$lib/components/startups';
  import { Can } from '$lib/components/shared';
  import { useQuery } from '@sveltestack/svelte-query';
  import { getData } from '$lib/utils.js';
  import * as Dialog from '$lib/components/ui/dialog';
  import Application from '$lib/components/startup/Application.svelte';
  import { page } from '$app/stores';
  import { toast } from 'svelte-sonner';
  import * as Accordion from '$lib/components/ui/accordion/index.js';

  let { data } = $props();

  const queryResult = useQuery('startupData', () =>
    getData(`/startups/startups`, data.access!)
  );

  const role: any = data.role;

  const isLoading = $derived($queryResult.isLoading);
  const isError = $derived($queryResult.isError);
  const hasStartups = $derived(
    Array.isArray($queryResult.data) && $queryResult.data.length > 0
  );
  const listOfStartups = $derived(
    $queryResult.isSuccess && hasStartups ? $queryResult.data : []
  );

  let showApplicationForm = $state(false);
  const toggleApplicationForm = () => {
    showApplicationForm = !showApplicationForm;
  };

  $effect(() => {
    const success = $page.url.searchParams.get('success');
    if (success === 'true') {
      toast.success('Application successfull.');
      const url = new URL($page.url.href);
      url.searchParams.delete('success');
      history.replaceState(null, '', url);
    }
  });

  // For search/filter UI (not functional for now)
  let search = '';
  let filter = 'All Startups';
</script>

<svelte:head>
  <title>ChumCheck - Startups</title>
</svelte:head>

<div class="flex items-center justify-between mb-8">
  <div>
    <h2 class="text-3xl font-bold">Startups</h2>
    <p class="text-muted-foreground">Manage assigned startups</p>
  </div>
  <Can role={['Startup']} userRole={role}>
    <div class="flex gap-5">
      <Button
        class="flex items-center justify-center gap-2 rounded-lg"
        onclick={toggleApplicationForm}
      >
        <RocketIcon class="h-4 w-4" /> Apply
      </Button>
    </div>
  </Can>
</div>

<!-- Statistics Cards -->
<div class="grid grid-cols-4 gap-5 mb-8">
  
  <div class="rounded-lg bg-background p-5 flex flex-col gap-2 border border-border">
    <div class="text-muted-foreground text-sm">Total Startups</div>
    <div class="flex items-center gap-2">
      <span class="text-2xl font-bold">{listOfStartups.length}</span>
    </div>
    <div class="flex items-center gap-2">
      <div class="flex flex-col items-center p-2 rounded-xl text-xs font-semibold border border-green-400 text-green-400 bg-green-950">
        <span>{listOfStartups.length}</span>
        <span>Active</span>
      </div>
      <div class="flex flex-col items-center p-2 rounded-xl text-xs font-semibold border border-blue-500 text-blue-500 bg-slate-900">
        <span>0</span>
        <span>Completed</span>
      </div>
      <div class="flex flex-col items-center p-2 rounded-xl text-xs font-semibold border border-yellow-400 text-yellow-400 bg-yellow-900">
        <span>0</span>
        <span>Paused</span>
      </div>
    </div>
  </div>

  <div class="rounded-lg bg-background p-5 flex flex-col gap-2 border border-border">
    <div class="text-muted-foreground text-sm">Initiatives Progress</div>
    <div class="flex items-center gap-2">
      <span class="text-2xl font-bold">51/93</span>
      <span class="ml-auto text-sm">53%</span>
    </div>
    <div class="w-full h-2 bg-gray-200 rounded">
      <div class="h-2 bg-blue-500 rounded" style="width:53%"></div>
    </div>
  </div>
  
  <div class="rounded-lg bg-background p-5 flex flex-col gap-2 border border-border">
    <div class="text-muted-foreground text-sm">Pending Consultations</div>
    <div class="flex items-center gap-2">
      <span class="text-2xl font-bold">4</span>
    </div>
    <div class="text-muted-foreground text-sm">Across 3 startups</div>
  </div>
  
  <div class="rounded-lg bg-background p-5 flex flex-col gap-2 border border-border">
    <div class="text-muted-foreground text-sm">Completion Rate</div>
    <div class="flex items-center gap-2">
      <span class="text-2xl font-bold">13%</span>
    </div>
    <div class="text-muted-foreground text-sm">1 of 7 startups completed</div>
  </div>
</div>

<!-- Search and Filters -->
<div class="mb-5">
  <div class="flex items-center gap-2 mb-2 w-[400px]">
    <div class="relative flex-1">
      <input
        class="w-full rounded-lg border border-[#2a3550] bg-background px-4 py-2 pr-12 text-sm text-white placeholder-[#b3bed7] focus:outline-none focus:ring-2 focus:ring-blue-500"
        type="text"
        placeholder="Search startups..."  
        bind:value={search}
      />
      <button
        class="absolute right-2 top-1/2 -translate-y-1/2 bg-[#2563eb] hover:bg-[#1d4ed8] rounded-lg p-2 transition-colors"
        tabindex="-1"
        type="button"
      >
        <img src="/magnifying_glass.png" alt="Search" class="h-4 w-4" />
      </button>
    </div>
  </div>
  <div class="flex gap-0.5 border border-border rounded w-fit">
    <button class="px-4 py-1.5 rounded-tl-lg rounded-bl-lg text-white text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-blue-500 {filter === 'All Startups' ? 'bg-[#2563eb] text-white font-bold' : ''}">
      All Startups
    </button>
    <button class="px-4 py-1.5 text-[#b3bed7] text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-blue-500 {filter === 'Active' ? 'bg-[#2563eb] text-white font-bold' : ''}">
      Active
    </button>
    <button class="px-4 py-1.5 text-[#b3bed7] text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-blue-500 {filter === 'Completed' ? 'bg-[#2563eb] text-white font-bold' : ''}">
      Completed
    </button>
    <button class="px-4 py-1.5 rounded-tr-lg rounded-br-lg text-[#b3bed7] text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-blue-500 {filter === 'Paused' ? 'bg-[#2563eb] text-white font-bold' : ''}">
      Paused
    </button>
  </div>
</div>


<!-- Startup Cards Grid -->
{#if isLoading}
  <div class="mt-3 grid grid-cols-4 gap-3">
    <div class="rounded-lg bg-background"><Skeleton class="h-40 rounded-lg" /></div>
    <div class="rounded-lg bg-background"><Skeleton class="h-40 rounded-lg" /></div>
    <div class="rounded-lg bg-background"><Skeleton class="h-40 rounded-lg" /></div>
  </div>
{:else if isError}
  <div>
    <p>Error fetching data. Contact support</p>
  </div>
{:else if hasStartups}
  <div class="mt-3 grid grid-cols-4 gap-5">
    {#each listOfStartups as startup}
      <StartupCard {startup} />
    {/each}
  </div>
{:else}
  <div class="mt-3 text-center text-muted-foreground">No startups found.</div>
{/if}

<Dialog.Root open={showApplicationForm} onOpenChange={toggleApplicationForm}>
  <Dialog.Content class="h-4/5 max-w-[700px]">
    <Application access={data.access!} />
  </Dialog.Content>
</Dialog.Root>

// client/src/app/(chumcheck)/startups/_components/Startups.tsx
'use client'
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { TaskStatus } from "@/lib/enums";
import { Startup } from "@/lib/types";
import { startupStatusMap } from "@/lib/utils";
import Image from "next/image";
import Link from "next/link";
import { useState } from "react";

export default function Startups({ startups }: { startups: Startup[] }) {

  const [search, setSearch] = useState("");
  const [filter, setFilter] = useState("All Startups");

  const filterStatusMap: Record<string, number[]> = {
    Qualified: [3],
    Pending: [1, 2],
    Rejected: [4],
    Paused: [5],
    Completed: [6],
  };

  const filteredStartups = startups.filter((startup) => {
    if (filter !== "All Startups" && !filterStatusMap[filter]?.includes(startup.qualificationStatus)) {
      return false;
    }
    if (search && !startup.name.toLowerCase().includes(search.toLowerCase())) {
      return false;
    }
    return true;

  });

  const filterNames = ["All Startups", "Qualified", "Pending", "Rejected", "Paused", "Completed"];

  return (
    <>
      <div className="mb-5">
        <div className="flex items-center gap-2 mb-2 w-[400px]">
          <div className="relative flex-1">
            <input
              className="w-full rounded-lg border border-gray-800 bg-background px-4 py-2 pr-12 text-sm text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500"
              type="text"
              placeholder="Search startups..."
              onChange={e => setSearch(e.target.value)}
            />

            {/* TODO: FIX HAHA */}
            {/* <Button className="absolute right-2 t-0 "> */}
            {/*   <Image src='/magnifying_glass.png' width={16} height={16} alt='Image of a magnifying glass' /> */}
            {/* </Button> */}
          </div>
        </div>
        <div className="flex gap-0.5 border border-border rounded-xl w-fit">
          {filterNames.map((filterName, index) => (
            <button
              key={filterName}
              onClick={() => setFilter(filterName)}
              className={`px-4 py-1.5 text-white text-xs font-semibold focus:outline-none focus:ring-2 focus:ring-blue-700
                          ${filter === filterName ? "bg-accent text-white font-bold" : ''}
                          ${index === 0 ? "rounded-tl-lg rounded-bl-lg" : ""} 
                          ${index === filterNames.length - 1 ? "rounded-tr-lg rounded-br-lg" : ""} `}
            >{filterName}</button>
          ))}
        </div>
      </div>

      <div className="mt-3 pb-10 grid grid-cols-4 gap-5">
        {filteredStartups.map(startup => (
          <Link key={startup.id} href={`/readinesslevel/${startup.id}`}>
          <Card className="h-40 w-auto cursor-pointer bg-background border border-gray-700 hover:bg-accent rounded-xl p-0 transition-colors duration-150">
            <CardContent className="h-full">
              <div className="flex flex-col h-full p-3 justify-between">
                <div className="flex items-center gap-3 mb-1 w-full">
                  <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#2563eb] text-white text-base font-bold">
                    {startup.name
                      .split(' ')
                      .map((word: string) => word.charAt(0).toUpperCase())
                      .join('')
                      .slice(0, 3)}
                  </div>
                  <span className="text-base font-semibold text-white truncate max-w-[120px]" title={startup.name}>
                    {startup.name.length > 10 ? startup.name.slice(0, 10) + '...' : startup.name}
                  </span>
                  <span className={`ml-auto border rounded px-2 py-0.5 text-xs font-semibold ${startupStatusMap[startup.qualificationStatus].border} ${startupStatusMap[startup.qualificationStatus].text} ${startupStatusMap[startup.qualificationStatus].bg}`}>
                    {startupStatusMap[startup.qualificationStatus].label}
                    {/* {status.label === 'Qualified' && role === 'Mentor' ? 'Active' : status.label} */}
                  </span>
                </div>
                <div className="flex items-center gap-2 text-xs text-[#b3bed7] mb-1">
                  Initiatives
                  <span className="ml-1 font-bold text-white">{startup.initiatives.filter(initiative => initiative.status === TaskStatus.Completed).length} / {startup.initiatives.length}</span>
                </div>
                <div className="w-full h-2 bg-gray-800 rounded mb-2">

                  <div
                    className={`h-2 bg-white rounded`}
                    style={{
                      width: `${startup.initiatives.length > 0
                        ? (startup.initiatives.filter(initiative => initiative.status === TaskStatus.Completed).length / startup.initiatives.length) * 100
                        : 0
                        }%`
                    }}
                  ></div>
                </div>
                <div className="flex items-center gap-2 text-xs text-[#b3bed7]">
                  <Image src="/checked.png" alt="Checked" width={16} height={16} />
                  <span className="text-[#b3bed7]">No consultation pending</span>
                </div>
              </div>
            </CardContent>
          </Card>
          </Link>
        ))}

      </div>
    </>
  )
}
