// client/src/components/landing/AboutUs.tsx
import Image from "next/image";

const AboutUs = () => {

  return (
    <div className="relative h-full w-full">
      <div
        className="absolute bottom-0 left-0 right-0 top-0 -z-10 bg-[linear-gradient(to_right,#ecf3fc_1px,transparent_1px),linear-gradient(to_bottom,#ecf3fc_1px,transparent_1px)] bg-[size:2.5rem_2.5rem] [mask-image:radial-gradient(ellipse_100%_50%_at_50%_50%,#000_70%,transparent_110%)] dark:bg-[linear-gradient(to_right,#171e31_1px,transparent_1px),linear-gradient(to_bottom,#171e31_1px,transparent_1px)]"
      ></div>

      <div className="mx-auto flex h-screen w-4/5 items-center justify-between" id="aboutus">
        <div className="flex flex-1 items-center text-flutter-gray dark:text-flutter-white">
          <div className="flex flex-1 flex-col gap-5">
            <p className="text-4xl font-extrabold">About Us</p>
            <p className="text-2xl font-medium">
              ChumCheck is a dedicated program designed to <br />support startups on their path to
              success. <br />It provides essential resources and guidance <br />to innovative
              entrepreneurs, with a specific focus <br />on incubation and acceleration.
            </p>
          </div>
          <div className="relative flex-1">
            <div
              className="absolute left-0 right-0 top-0 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-flutter-blue opacity-20 blur-[100px]"
            ></div>
            <Image
              src="/aboutus.svg"
              alt="startup"
              width={100}
              height={100}
              className="w-full" />
          </div>
        </div>
      </div>
    </div>
  )

}

export default AboutUs;

// frontend/src/lib/components/landing/AboutUs.svelte
<div class="relative h-full w-full">
  <div
    class="absolute bottom-0 left-0 right-0 top-0 -z-10 bg-[linear-gradient(to_right,#ecf3fc_1px,transparent_1px),linear-gradient(to_bottom,#ecf3fc_1px,transparent_1px)] bg-[size:2.5rem_2.5rem] [mask-image:radial-gradient(ellipse_100%_50%_at_50%_50%,#000_70%,transparent_110%)] dark:bg-[linear-gradient(to_right,#171e31_1px,transparent_1px),linear-gradient(to_bottom,#171e31_1px,transparent_1px)]"
  ></div>

  <div
    class="mx-auto flex h-screen w-4/5 items-center justify-between"
    id="aboutus"
  >
    <div
      class="flex flex-1 items-center text-flutter-gray dark:text-flutter-white"
    >
      <div class="flex flex-1 flex-col gap-5">
        <p class="text-4xl font-extrabold">About Us</p>
        <p class="text-2xl font-medium">
          ChumCheck is a dedicated program designed to <br />support startups on
          their path to success. <br />It provides essential resources and
          guidance <br />to innovative entrepreneurs, with a specific focus
          <br />on incubation and acceleration.
        </p>
      </div>
      <div class="relative flex-1">
        <div
          class="absolute left-0 right-0 top-0 -z-10 m-auto h-[310px] w-[310px] rounded-full bg-flutter-blue opacity-20 blur-[100px]"
        ></div>
        <img src="/aboutus.svg" alt="startup" class="w-full" />
      </div>
    </div>
  </div>
</div>
