// client/src/components/landing/Header.tsx
import Image from "next/image";
import Link from "next/link";

const Header = () => {

  return (
    <header
      className="fixed left-1/2 top-0 z-10 flex h-16 w-screen -translate-x-1/2 justify-center text-flutter-gray transition-all duration-300 ease-in-out dark:text-flutter-white"
    >
      <nav className="flex h-16 w-4/5 items-center p-[var(--navbar-padding,0.5rem)] px-0">
        <div className="flex flex-1 cursor-pointer gap-2">
          <Image
            src="/logo.png"
            alt="citeams_logo"
            className="h-7 w-7"
            width={167 / 5}
            height={165 / 5}
          />
          <Link href="/" className="cursor-pointer text-xl font-black normal-case">ChumCheck</Link>
        </div>
        <div className="flex-none font-medium">
          <ul className="flex flex-1 cursor-pointer items-center gap-7 text-[15px]">
            <li className="hover:text-flutter-blue active:scale-95">
              <Link href="#hero">Home</Link>
            </li>
            <li className="hover:text-flutter-blue active:scale-95">
              <Link href="#howitwork">How it Works</Link>
            </li>
            <li className="hover:text-flutter-blue active:scale-95">
              <Link href="#aboutus">About Us</Link>
            </li>
            <li className="hover:text-flutter-blue active:scale-95">
              <Link data-sveltekit-reload href="/login">Login</Link>
            </li>
          </ul>
        </div>
      </nav>
    </header>
  )
}

export default Header;

// frontend/src/lib/components/shared/header.svelte
<script lang="ts">
  import Button from '$lib/components/ui/button/button.svelte';
  import * as Avatar from '$lib/components/ui/avatar';
  import * as DropdownMenu from '$lib/components/ui/dropdown-menu';
  import { Badge } from '$lib/components/ui/badge';
  import { access } from '$lib/access';
  import { page } from '$app/stores';
  import { Separator } from '$lib/components/ui/separator';
  import { crossfade } from 'svelte/transition';
  import { cubicInOut } from 'svelte/easing';
  import { onMount } from 'svelte';
  import { getProfileColor, getRole } from '$lib/utils';

  const { user, startup } = $props();

  const userRole = getRole(user.role);
  const modules =
    access.roles[`${userRole as 'Startup' | 'Mentor' | 'Manager'}`].modules;

  4;
  const currentModule = $derived(
    $page.url.pathname.slice(1).split('/')[
      $page.url.pathname.slice(1).split('/').length - 1
    ]
  );

  const currentModulev2 = $derived(
    $page.url.pathname.slice(1).split('/')[
      $page.url.pathname.slice(1).split('/').length - 2
    ]
  );

  const module = $derived($page.url.pathname.slice(1).split('/')[0]);
  const subModule = $derived(
    $page.url.pathname.slice(1).split('/')[
      $page.url.pathname.slice(1).split('/').length - 1
    ]
  );

  const [send, receive] = crossfade({
    duration: 250,
    easing: cubicInOut
  });

  let isBlurred = $state(false);

  function handleScroll() {
    const scrollY = window.scrollY;

    isBlurred = scrollY > 100;
  }

  onMount(() => {
    window.addEventListener('scroll', handleScroll);

    return () => {
      window.removeEventListener('scroll', handleScroll);
    };
  });
</script>

<header
  class="fixed left-1/2 top-0 z-10 flex h-16 w-screen -translate-x-1/2 justify-center border-b text-flutter-gray backdrop-blur-lg dark:text-flutter-white"
  class:backdrop-blur-lg={isBlurred}
>
  <nav class="flex h-16 w-4/5 items-center px-0">
    <div class="flex flex-1 cursor-pointer gap-2">
      <img src="/logo.png" alt="citeams_logo" class="h-7 w-7" />
      <a
        data-sveltekit-preload-data="tap"
        href={`/${modules[0].link}`}
        class="cursor-pointer text-xl font-black normal-case">ChumCheck</a
      >
    </div>
    <div class="flex h-1/3 items-center justify-center gap-5">
      <ul class="flex flex-1 cursor-pointer items-center gap-7 text-sm">
        {#if module !== subModule && module !== 'account' && subModule !== 'pending'}
          <!-- submodule -->
          {#each modules.filter((item) => item.link === module)[0].subModule as item}
            {@const isActive =
              currentModule === item.link || currentModulev2 === item.link}
            <a
              data-sveltekit-preload-data="tap"
              href={`/${module}/${startup}/${item.link}${item.name === 'Overview' ? `/${item?.subModule[0].link}` : ''}`}
              class="relative flex h-16 items-center justify-center text-center hover:text-flutter-blue active:scale-95"
              class:text-flutter-blue={currentModule === item.link ||
                currentModulev2 === item.link}
            >
              <li>
                {item.name}
                {#if isActive}
                  <div
                    class="absolute bottom-0 h-[1px] w-full bg-flutter-blue"
                    in:send={{ key: 'active-sidebar-tab' }}
                    out:receive={{ key: 'active-sidebar-tab' }}
                  ></div>
                {/if}
              </li>
            </a>
          {/each}
        {:else}
          <!-- module -->
          {#each modules as item}
            {@const isActive =
              currentModule === item.link || currentModulev2 === item.link}
            <a
              data-sveltekit-preload-data="tap"
              href={`/${item.link}${item.subModule.length > 0 && item.name !== 'Startups' ? `/${item.subModule[0].link}` : ''}`}
              class="relative flex h-16 items-center justify-center text-center hover:text-flutter-blue active:scale-95"
              class:text-flutter-blue={currentModule === item.link ||
                currentModulev2 === item.link}
            >
              <li>
                {item.name}
                {#if isActive}
                  <div
                    class="absolute bottom-0 h-[1px] w-full bg-flutter-blue"
                  ></div>
                {/if}
              </li>
            </a>
          {/each}
        {/if}
      </ul>
      <Separator orientation="vertical" />
      <Badge
        variant="outline"
        class="h-8 rounded-full bg-flutter-gray/20 text-sm font-normal"
        >{user?.role ? user?.role : 'Anonymous'}</Badge
      >
      <DropdownMenu.Root>
        <DropdownMenu.Trigger>
          <div
            class={`flex h-9 w-9 items-center justify-center rounded-full ${getProfileColor(user.firstName)}`}
          >
            {user.firstName.charAt(0)}
          </div>
        </DropdownMenu.Trigger>
        <DropdownMenu.Content align="end">
          <DropdownMenu.Group>
            <DropdownMenu.Label>
              <p>My Account</p>
              <p class="text-xm font-normal">{user?.email}</p>
            </DropdownMenu.Label>
            <DropdownMenu.Separator />
            {#each modules as module}
              <a
                class="cursor-pointer"
                data-sveltekit-preload-data="tap"
                href={`/${module.link}${module.subModule.length > 0 && module.name !== 'Startups' ? `/${module.subModule[0].link}` : ''}`}
              >
                <DropdownMenu.Item class="cursor-pointer"
                  >{module.name}</DropdownMenu.Item
                >
              </a>
            {/each}
            <form action="/logout" method="post" class="w-full">
              <button type="submit" class="w-full">
                <DropdownMenu.Item class="cursor-pointer"
                  >Logout</DropdownMenu.Item
                >
              </button>
            </form>
          </DropdownMenu.Group>
        </DropdownMenu.Content>
      </DropdownMenu.Root>
    </div>
  </nav>
</header>
